stages:
  - deploy

deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh-client sshpass
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
    - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
  script:
    - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER"@"$SERVER_HOST" "cd /home/garuda/smartthink && chmod +x build.sh && nohup ./build.sh > /dev/null 2>&1 &"
  only:
    - main
