stages:
  - deploy

deploy_production:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add --no-cache openssh-client sshpass
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
    - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
  script:
    - |
      sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_HOST" '
      cd /home/garuda/smartthink &&
      git pull origin main &&
      npm install --force &&
      git restore package-lock.json &&
      export NODE_OPTIONS=--max-old-space-size=4096 &&
      npm run build &&
      pm2 delete nextjs-glearning || true &&
      pm2 start npm --name "nextjs-glearning" -- start -- -p 3000
      '
  only:
    - main
